//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsVenueBookingCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duration
    {
        public int duration_Id { get; set; }
        public string duration_Name { get; set; }
        public System.TimeSpan duration_StartTime { get; set; }
        public System.TimeSpan duration_EndTime { get; set; }
        public long duration_User { get; set; }
        public bool duration_IsDel { get; set; }
    
        public virtual User User { get; set; }
    }
}
