//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsVenueBookingCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public long reservation_Id { get; set; }
        public long reservation_User { get; set; }
        public System.DateTime reservation_StartTime { get; set; }
        public System.DateTime reservation_EndTime { get; set; }
        public bool reservation_IsBilling { get; set; }
        public long reservation_Snooker { get; set; }
        public bool reservation_IsDel { get; set; }
    
        public virtual Snooker Snooker { get; set; }
        public virtual User User { get; set; }
    }
}
