//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsVenueBookingCommon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Durations = new HashSet<Duration>();
            this.Reservations = new HashSet<Reservation>();
            this.Snookers = new HashSet<Snooker>();
            this.Spaces = new HashSet<Space>();
        }
    
        public long user_Id { get; set; }
        public string user_UserNumber { get; set; }
        public string user_Password { get; set; }
        public int user_Type { get; set; }
        public string user_Class { get; set; }
        public string user_Name { get; set; }
        public bool user_Status { get; set; }
        public string user_Remark { get; set; }
        public bool user_IsDel { get; set; }
    
        public virtual ICollection<Duration> Durations { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<Snooker> Snookers { get; set; }
        public virtual ICollection<Space> Spaces { get; set; }
    }
}
